---
application_name: SafetyOS
business_name: Safety Plus Inc.
business_address: 2301 Lakeview Blvd, Denton, TX, USA
domain: example.com
support_email: support@example.com
default_from_email: My App <no-reply@example.com>
background_job_processor: sidekiq
email_provider: 
personal_accounts: true
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
multitenancy:
gems:
